### PR TITLE
Add new Makefile implementation, which can be used locally

### PR DESCRIPTION
**Pull request by tarsius**
~~This is still under construction,~~ *Update:* See description below.

 but I needed a place to make the following request:

@npostavs Could you please rebuild the `emacs` binaries `--with-modules`? You might also want to enable issues on https://github.com/npostavs/emacs-travis. *Update:* I assume you do not intend to build any macOS binaries. If you could do that, that would be nice though.

### CODE REVIEW

**Comment by tarsius** [comment]
Updated description:

```
This new implementation is based on the same template that I use for
most of my packages.  It is suitable for building the package locally.

The old Emake-based implementation was not suitable for local use,
because it contained no target to fetch the necessary Emake tools,
which is being done in ".travis.yml".  It would have been possible to
fix that, but since I have other reservations about Emake, I decided
otherwise.

Emake currently does not support "make -f MAKEFILE", so "both
makefiles" have to be located inside the same actual "Makefile" for
the time being.  The two implementations are separated from each other
using an `ifeq'.

Continue to use Emake on Travis because it supports building on macOS,
which the setup that I usually use hasn't been taught about.  Also the
binaries I currently use for other packages were not build with
support for modules.
```

**Comment by tarsius** [comment]
@TheBB I hope you are okay with this.

**Comment by vermiculus** [comment]
I am skeptical of the claim that emake does not support `-f` as I was able to do just that in the forge implementation. Is this still a problem?

**Comment by tarsius** [comment]
I have tried. I have just redone that on top of this branch, resulting in the error you can see above about `subr-x` not being available. `libgit` doesn't depend on `subr-x`, `emake` itself does. Please look into that.

**Comment by npostavs** [comment]
> Could you please rebuild the `emacs` binaries `--with-modules`?
> You might also want to enable issues on https://github.com/npostavs/emacs-travis.

Done and done.

> _Update:_ I assume you do not intend to build any macOS binaries. If you could do that, that would be nice though.

Yeah, the problem is I don't use macOS at all, so I'm not familiar with the process, and I wouldn't be able to debug locally.

**Comment by tarsius** [comment]
I have merged this now.

> I am skeptical of the claim that emake does not support `-f` as I was able to do just that in the forge implementation. Is this still a problem?

Yes, I couldn't get it to work. But I have updated the TODO to say that it is supposed to be supported but that I could not get it work instead of saying that it is not supported at all.

My failed attempt is in `split-makefile`.

> Done and done.

Thanks!

**Pull request merged**
