### PR TITLE
Reset

### PR DESCRIPTION
**Pull request by asavonic**

### CODE REVIEW

**Comment by asavonic** [comment]
@TheBB, looks like memtest-1 is a bit unstable.

**Comment by TheBB** [comment]
Yeah I was afraid of something like that. I'll disable them.

**Comment by TheBB** [comment]
Thank you for this. Looks good to me. Just two things: could you indent by four spaces, and turn the `TYPE` parameter into a symbol? I do it [like this](https://github.com/magit/libegit2/blob/master/src/egit-object.c#L28-L42).

**Comment by asavonic** [comment]
Sure, fixed.

**Comment by TheBB** [comment]
Great, thanks.

**Pull request merged**
