### PR TITLE
Blame overhaul

### PR DESCRIPTION
**Pull request by TheBB**
This PR reworks some of the blame system to bring it in line with practices we've established in other parts of libegit2 since it was written.

- Don't return a hunk as an alist, but as an opaque object with getters.
- Standardize option parsing (e.g. don't get flags as a list of symbols, but each flag separately as a bool)

### CODE REVIEW

**Comment by asavonic** [comment]
@TheBB, can you clarify the practices that you suggest to follow? I'm mostly concerned about an alist vs an opaque object.

Alist is a native data structure in Emacs, so you can basically `describe-variable` to see an alist in a human readable form. Getters are a bit harder to use, and they seem to introduce more boilerplate in libegit C code. We can wrap getters to alist in libegit.el later, as this seems to be a case of "Quality-of-life convenience functionality is better implemented in Emacs Lisp than in C" mentioned in the README.

**Comment by TheBB** [comment]
Sure, I talked about this in more detail in #42.

Totally agree with all your comments though, basically my reasoning went as follows:

- Avoid copying data without being asked (libgit2 sometimes goes to great lengths to re-use objects for performance)
- Consistency, I want to deviate from libgit2 as little as possible
- We can't avoid opaque objects anyway
- Practically this entire library is boilerplate

When we reach a certain stage of completion we should have a discussion about where to draw the line between elisp and C, but until then I think I'd like to commit to a pretty limited level of "magic" so that the effort can go toward coverage.

When that time comes, things to discuss:

- Whether we can be more flexible with input types, specifically accepting git objects or ID strings, reference objects or reference name strings, and so on. This could help us cut back on the amount of functions needed, too. Even now there are dumb duplicates like `libgit-object-id`, `libgit-commit-id`, `libgit-tree-id` etc, which do entirely the same thing except the latter two error out on unexpected types.
- Whether we can return more lispy data structures without going through an opt-in translation function.
- Whether all the functions that need to parse option structures (like here with blame) can accept keyword arguments instead of alists. This isn't really doable with the dispatches that I wrote in *egit.c* so we'd have to implement something akin to `&rest`. Not really that difficult to be honest.

That's what comes to mind at the moment. Once @tarsius has more experience using libgit in elisp we will understand more clearly what we want.

**Comment by asavonic** [comment]
Thank you. This makes perfect sense, and I will follow this
approach going forward.

**Comment by TheBB** [comment]
Great! :+1:

**Pull request merged**
