### PR TITLE
Add signature_default function

### PR DESCRIPTION
**Pull request by sdubinsky**
I'm pretty sure I need this and the related object for the commit stuff.  It compiles and the test runs, but I couldn't figure out how to extract the name/email from the signature object in the test.  Do I just need to define a `signature_get_name` function in `egit-signature.c`?

The "merge pull request 1" commit was my attempt to get my fork in line with master here.  I don't think I did it right.

### CODE REVIEW

**Comment by sdubinsky** [comment]
I guess most of this is actually pulled out of the commit_create branch, but the signature_default function is new.

**Comment by TheBB** [comment]
It makes sense to merge this before the commit_create stuff I suppose. The comments I made there about signatures and repository objects still applies here though.

**Comment by sdubinsky** [comment]
I apologize for all the messy commits - this is my first time using github pull requests at all.

**Comment by TheBB** [comment]
Thanks! I rebased, squashed and merged manually, with some fixes on top.

**Pull request closed without merging**
